name = "cs-order-api"
main = "src/index.ts"
compatibility_date = "2024-06-03"
account_id = "ed15f9571e683538b4f05e88d389c9dc"

# 启用 Observability
[observability]
enabled = true
head_sampling_rate = 1

# D1数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "cs-order-db"
database_id = "e03be497-4138-4135-aca3-bd4367ba092e"

# 环境变量
[vars]
DEFAULT_SERVICE_STAFF = "客服"
CORS_ORIGIN = "*"
